### ISSUE TITLE
Fix runtest alias for esy installation

### ISSUE THREAD

**Issue by jchavarri** [melange-re/melange#126]
If I run:

```
esy dune build @runtest
```

I get:

```
Error: Cannot find module 'web-tree-sitter'
Require stack:
- /home/javier.chavarri/code/melange/_esy/default/store/b/melange-9f11211a/default/ocaml-tree/wasm.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
...
```

It'd be nice to have esy run tests in ci as well.

**Comment by anmonteiro** [comment]
See [this comment](https://github.com/melange-re/melange/blob/fork/jscomp/core/dune#L29) for context

**Comment by bikallem** [comment]
Interesting, what is the `web-tree-sitter` used for?

**Comment by jchavarri** [comment]
It replaced camlp4: https://github.com/rescript-lang/rescript-compiler/pull/4910

Afaik (which is not much) it's used in the compiler internals to facilitate JS output code generation.

**Comment by EduardoRFS** [comment]
Will fix that for us, another advantage of this is running the tests on macOS ARM64

**Comment by anmonteiro** [comment]
> There is also https://github.com/returntocorp/ocaml-tree-sitter which generates ocaml CST if that was the purpose of `web-tree-sitter`.

oh! I wasn't aware of this. Perhaps we could replace that last node dependency with an OCaml script.

**Comment by EduardoRFS** [comment]
The problem is only because of `web-tree-sitter`, so if you want to run the tests and don't care about the promoted rules, you can just call `dune runtest --ignore-promoted-rules`.

#153 will enable the tests on the CI with ersy
