### ISSUE TITLE
Can't run bsc at development environment in Node.js 12.x

### ISSUE THREAD

**Issue by renatoalencar** [melange-re/melange#176]
I'm having this little problem with trying to compile a simple OCaml file to Javascript,
it looks like this is happening because the code of the error bellow is using optional
chaining, which is only supported on Node.js 14.x+. Although Node.js 12.x is ending
its maintenance lifecycle by Apr 2022, I believe until there it would be useful to support
this version.

The code I was trying to test has nothing to do with the Node.js version, so I was able
to successfuly compile that just replacing the optional chaining by a short circuited and
operator.

Another option is to explicitely tell that this project needs Node.js 14 in order to run
in development environment, or even add a .nvmrc file on the project root.

```
/home/[redacted]/workspace/melange/_esy/default/store/b/melange-ce067297/default/ocaml-tree/fold_maker.js:109
  assert(branch?.type === "constructor_declaration");
                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/[redacted]/workspace/melange/_esy/default/store/b/melange-ce067297/default/ocaml-tree/wasm.js:38:18)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

The command I've run:

```
 esy dune exec jscomp/main/js_main.exe examples.install/HelloWorldOne.ml
```

**Comment by anmonteiro** [comment]
ah I wasn't aware of this.

This should be fixed soon after, @joseeMDS is working on converting the tree-sitter generation to an OCaml executable

**Comment by EduardoRFS** [comment]
The version of tree-sitter is pinned at https://github.com/melange-re/melange/blob/fork/esy.json counsciously
