### ISSUE TITLE
[playground]: better runtime error display

### ISSUE THREAD

**Issue by anmonteiro** [melange-re/melange#681]
In this case:

https://melange.re/unstable/playground/?language=OCaml&code=ZXh0ZXJuYWwgemVyb19hcml0eSA6IHVuaXQgLT4gaW50ID0gIm1hcCIKICBbQEBicy52YWxdCgpsZXQgYXBwbGllc191bmRlZmluZWQgZm9vID0gSnMubG9nIGZvbwoKbGV0IHQgPSB6ZXJvX2FyaXR5ICgpCmxldCAoKSA9IGFwcGxpZXNfdW5kZWZpbmVkICgp&live=off

The "console" panel shows the following:

```
{"stack":"ReferenceError: map is not defined\n at eval (eval at <anonymous> (https://melange.re/unstable/playground/assets/worker-73317288.js:59703:70934), <anonymous>:11:11)\n at eval (eval at <anonymous> (https://melange.re/unstable/playground/assets/worker-73317288.js:59703:70934), <anonymous>:21:3)\n at eval (<anonymous>)\n at https://melange.re/unstable/playground/assets/worker-73317288.js:59703:70934\n at async https://melange.re/unstable/playground/assets/worker-73317288.js:59649:13995\n at async Object.write (https://melange.re/unstable/playground/assets/worker-73317288.js:59649:13974)","message":"map is not defined"}
```

This should be presented in a more readable way

**Comment by anmonteiro** [comment]
Thanks!
